### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by TasMot** [alphadev-net/ntfslib#1]
Could you add an example/test that shows how to use this project? For example, how to write and then read an arbitrary file? I think this is just what I need, but I can't find a way to read/write my files. My use case is that I have a file stored as a resource in the resource folder during testing, and in the jar file once completed. 
The package I'm using insists on using a file as input. So, I need to load the resource (which is a .csv file), then write it to the RamDisk, then tell the package to read the file from the RamDisk via the file name. How to I create a java "File  myCsvFile = new File("CsvFileOnRamdisk.csv").

Thanks,
Tom

**Comment by janseeger** [comment]
I'm afraid this library is not for you then. This is a low-level library that given a raw disk image in the NTFS format can then read those. You probably want to find a way to resolve the file in its location via class loader tricks.

That being said, this lib is not in any shape to be used productively and I won't find the time to continue working on it in the future. I do not recommend you use it.

**Comment by TasMot** [comment]
Thanks for the reply, I did move on to something else.
